version: "3.7"

services:
    with_ddos_prevention:
        container_name: with_ddos_prevention
        restart: always
        ports:
            - 3000:3000
        build:
            context: ./with_ddos_prevention
            dockerfile: Dockerfile
    
    without_ddos_prevention:
        container_name: without_ddos_prevention
        restart: always
        ports:
            - 4000:4000
        build:
            context: ./without_ddos_prevention
            dockerfile: Dockerfile